(()=>{
  const runs=window.LORE_RESEARCH_ENDPOINT||'https://lore-host.d.onjrnm.link/api/v1/research/runs';
  const waitlistEndpoint=window.LORE_WAITLIST_ENDPOINT||'https://lore-host.d.onjrnm.link/waitlist';
  const $=id=>document.getElementById(id),launch=$('lore-launch'),widget=$('lore-widget'),close=$('lore-widget-close'),capture=$('lore-capture'),compose=$('lore-compose'),email=$('lore-email'),input=$('lore-message'),thread=$('lore-thread'),capNote=$('lore-capture-note'),chatNote=$('lore-chat-note'),state=$('lore-widget-state');
  if(!launch||!widget)return;
  let busy=false;
  const suggestions=[
    'Research me and my firm from primary sources. Find one non-obvious reason Lore fits our thesis, cite every source, and write a short brief.',
    'Find a current market number for AI agents in workplace chat. Read the original source, explain what it actually measures, and cite it.',
    'Research three recent team-chat AI launches from official sources. Compare what really shipped and build a concise memo.'
  ];
  function installPromptShelf(){const first=thread.querySelector('.lore-msg');if(!first)return;const copy=first.querySelector('.lore-copy');copy.textContent='I’m Lore, an AI that does real work from inside the group chat. Give me a research or writing task and watch the searches, sources, and artifact appear here.';const shelf=document.createElement('div');shelf.className='lore-suggestions';suggestions.forEach((text,i)=>{const b=document.createElement('button');b.type='button';b.textContent=['research me','pull a market number','compare recent launches'][i];b.onclick=()=>{if(!compose.classList.contains('active')){email.focus();capNote.textContent='Enter your email once, then this prompt will be ready.';input.value=text;return}input.value=text;input.focus()};shelf.append(b)});copy.append(shelf)}
  installPromptShelf();
  const absolute=url=>new URL(url,'https://lore-host.d.onjrnm.link').href;
  function toggle(open){widget.classList.toggle('open',open);widget.setAttribute('aria-hidden',String(!open));launch.setAttribute('aria-expanded',String(open));if(open)(compose.classList.contains('active')?input:email).focus()}
  function row(who='lore'){const el=document.createElement('div');el.className='lore-msg'+(who==='you'?' user':'');el.innerHTML=who==='you'?'<div><div class="lore-who">you</div><div class="lore-copy"></div></div>':'<div class="lore-avatar">l</div><div><div class="lore-who">lore</div><div class="lore-copy"></div></div>';thread.append(el);return el}
  function add(text,who='lore'){const el=row(who);el.querySelector('.lore-copy').textContent=text;scroll();return el}
  function scroll(){thread.scrollTop=thread.scrollHeight}
  function eventNode(event){const el=document.createElement('div');el.className='lore-run-event';el.dataset.eventId=event.id;const dot=document.createElement('i'),body=document.createElement('div'),label=document.createElement('b'),detail=event.url?document.createElement('a'):document.createElement('span');label.textContent=event.label||event.type;detail.textContent=event.detail||'';if(event.url){detail.href=event.url;detail.target='_blank';detail.rel='noopener noreferrer'}body.append(label,detail);el.append(dot,body);return el}
  function proofCard(item,kind){const a=document.createElement('a');a.className='lore-proof '+kind;a.href=absolute(item.url);a.target='_blank';a.rel='noopener noreferrer';const label=document.createElement('span'),title=document.createElement('b'),meta=document.createElement('small');label.textContent=kind==='artifact'?'ARTIFACT':'SOURCE';title.textContent=item.title||item.url;meta.textContent=item.domain||item.type||new URL(a.href).hostname;a.append(label,title,meta);return a}
  async function json(r){try{return await r.json()}catch{return {error:'Lore returned unreadable run data.'}}}
  function render(snapshot,run){state.textContent=snapshot.status==='queued'?(snapshot.queue_position?`queued · ${snapshot.queue_position}`:'queued'):snapshot.status==='running'?'working':snapshot.status||'online';(snapshot.events||[]).forEach(event=>{if(event.id&&!run.seen.has(event.id)){run.seen.add(event.id);run.events.append(eventNode(event));scroll()}});if(snapshot.status==='completed'&&snapshot.result&&!run.finished){run.finished=true;run.wait.remove();const answer=add(snapshot.result.answer||'Research complete.');answer.classList.add('lore-answer');const sources=snapshot.result.sources||[],artifacts=snapshot.result.artifacts||[];if(sources.length){const group=document.createElement('div');group.className='lore-proofs';sources.forEach(x=>group.append(proofCard(x,'source')));answer.querySelector('.lore-copy').append(group)}if(artifacts.length){const group=document.createElement('div');group.className='lore-proofs';artifacts.forEach(x=>group.append(proofCard(x,'artifact')));answer.querySelector('.lore-copy').append(group)}state.textContent='run complete';scroll()}if(['failed','cancelled'].includes(snapshot.status))throw new Error(snapshot.error||'The research run stopped.')}
  async function send(task){if(busy)return;busy=true;chatNote.className='lore-note';chatNote.textContent='';compose.querySelector('button').disabled=true;add(task,'you');const shell=row(),copy=shell.querySelector('.lore-copy'),events=document.createElement('div');events.className='lore-run-events';const wait=document.createElement('div');wait.className='lore-run-wait';wait.innerHTML='<span class="lore-typing"><i></i><i></i><i></i></span><span> Lore is working</span>';copy.append(events,wait);const run={events,wait,seen:new Set(),finished:false};state.textContent='starting research';try{const r=await fetch(runs,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task})}),first=await json(r);if(!r.ok)throw new Error(first.error||`Run rejected (${r.status})`);if(!first.run_id)throw new Error('Lore returned no run ID.');render(first,run);const statusUrl=absolute(first.status_url||`${runs}/${first.run_id}`);let snap=first;while(!['completed','failed','cancelled'].includes(snap.status)){await new Promise(x=>setTimeout(x,1200));const sr=await fetch(statusUrl,{headers:{Accept:'application/json'}});snap=await json(sr);if(!sr.ok)throw new Error(snap.error||`Run status failed (${sr.status})`);render(snap,run)}}catch(err){if(!run.finished){run.wait.remove();const e=document.createElement('div');e.className='lore-run-error';e.textContent=err.message||'Lore could not complete the run.';copy.append(e)}state.textContent='run stopped';chatNote.className='lore-note error';chatNote.textContent='Nothing was fabricated. Try a narrower research task.'}finally{busy=false;compose.querySelector('button').disabled=false;input.focus();scroll()}}
  launch.onclick=()=>toggle(!widget.classList.contains('open'));close.onclick=()=>toggle(false);document.addEventListener('keydown',e=>{if(e.key==='Escape')toggle(false)});capture.onsubmit=async e=>{e.preventDefault();if(!email.reportValidity())return;const button=capture.querySelector('button');button.disabled=true;capNote.className='lore-note';capNote.textContent='saving...';try{await fetch(waitlistEndpoint,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify({email:email.value.trim(),source:'landing-chat-widget'})});capture.style.display='none';compose.classList.add('active');input.placeholder='Ask Lore to research something current';input.focus()}catch(err){capNote.className='lore-note error';capNote.textContent='Could not save your email. Try again.'}finally{button.disabled=false}};compose.onsubmit=e=>{e.preventDefault();const m=input.value.trim();if(!m)return;input.value='';send(m)};input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();compose.requestSubmit()}};
})();
