(()=>{
  // Relative by default. Override before loading with window.LORE_CHAT_ENDPOINT.
  const endpoint=window.LORE_CHAT_ENDPOINT||'https://lore-host.onrender.com/api/v1/chat';
  const waitlistEndpoint=window.LORE_WAITLIST_ENDPOINT||'https://lore-host.onrender.com/waitlist';
  const $=id=>document.getElementById(id),launch=$('lore-launch'),widget=$('lore-widget'),close=$('lore-widget-close'),capture=$('lore-capture'),compose=$('lore-compose'),email=$('lore-email'),input=$('lore-message'),thread=$('lore-thread'),capNote=$('lore-capture-note'),chatNote=$('lore-chat-note'),state=$('lore-widget-state');
  let sessionId='',busy=false;
  function toggle(open){widget.classList.toggle('open',open);widget.setAttribute('aria-hidden',String(!open));launch.setAttribute('aria-expanded',String(open));if(open)(compose.classList.contains('active')?input:email).focus()}
  function add(text,who='lore',typing=false){const row=document.createElement('div');row.className='lore-msg'+(who==='you'?' user':'');row.innerHTML=who==='you'?'<div><div class="lore-who">you</div><div class="lore-copy"></div></div>':'<div class="lore-avatar">l</div><div><div class="lore-who">lore</div><div class="lore-copy"></div></div>';const c=row.querySelector('.lore-copy');typing?c.innerHTML='<span class="lore-typing"><i></i><i></i><i></i></span>':c.textContent=text;thread.append(row);thread.scrollTop=thread.scrollHeight;return row}
  async function send(message){if(busy)return;busy=true;chatNote.className='lore-note';chatNote.textContent='';compose.querySelector('button').disabled=true;add(message,'you');const wait=add('','lore',true);state.textContent='thinking';try{const body={message};if(sessionId)body.session_id=sessionId;const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Lore is offline right now.');if(!data.reply)throw new Error('Lore sent an empty reply.');wait.querySelector('.lore-copy').textContent=data.reply;sessionId=data.session_id||sessionId}catch(err){wait.remove();chatNote.className='lore-note error';chatNote.textContent=err.message||'Could not reach Lore. Try again.'}finally{busy=false;state.textContent='online';compose.querySelector('button').disabled=false;input.focus();thread.scrollTop=thread.scrollHeight}}
  launch.onclick=()=>toggle(!widget.classList.contains('open'));close.onclick=()=>toggle(false);document.addEventListener('keydown',e=>{if(e.key==='Escape')toggle(false)});capture.onsubmit=async e=>{e.preventDefault();if(!email.reportValidity())return;const button=capture.querySelector('button');button.disabled=true;capNote.className='lore-note';capNote.textContent='saving...';try{await fetch(waitlistEndpoint,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify({email:email.value.trim(),source:'landing-chat-widget'})});capture.style.display='none';compose.classList.add('active');input.focus()}catch(err){capNote.className='lore-note error';capNote.textContent='Could not save your email. Try again.'}finally{button.disabled=false}};compose.onsubmit=e=>{e.preventDefault();const m=input.value.trim();if(!m)return;input.value='';send(m)};input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();compose.requestSubmit()}};
})();
