(()=>{
  // Same-origin by default. Override with a base such as https://lore-host.d.onjrnm.link.
  const base=(window.LORE_API_BASE||'https://lore-host.d.onjrnm.link').replace(/\/$/,'');
  const $=id=>document.getElementById(id),auth=$('auth'),form=$('auth-form'),guidInput=$('guid'),app=$('app'),nav=$('nav'),content=$('content');
  let guid=new URLSearchParams(location.search).get('chat')||localStorage.getItem('lore_memory_chat_guid')||'',model=[];
  function item(text,kind,meta=''){return {text:String(text||''),kind,meta}}
  function normalize(d){const sections=[];sections.push({key:'facts',label:'Group facts',items:(d.facts||[]).map(x=>item(x,'fact'))});const people=[];Object.entries(d.people||{}).forEach(([name,facts])=>(facts||[]).forEach(x=>people.push(item(x.fact,'person',name))));sections.push({key:'people',label:'People',items:people});sections.push({key:'tasks',label:'Open tasks',items:(d.open_tasks||[]).map(x=>item(x.spec||x.kind||x.id,x.kind||'task',x.status||''))});sections.push({key:'docs',label:'Docs',items:(d.docs||[]).map(x=>item(x.title||x.id,'doc'))});return sections}
  function show(key){const s=model.find(x=>x.key===key)||model[0];[...nav.children].forEach(b=>b.classList.toggle('active',b.dataset.key===s.key));const box=document.createElement('section'),head=document.createElement('div'),h=document.createElement('h2'),count=document.createElement('span'),items=document.createElement('div');head.className='section-head';h.textContent=s.label;count.className='count';count.textContent=`${s.items.length} items`;head.append(h,count);box.append(head);items.className='items';if(!s.items.length){items.className='empty';items.replaceChildren(Object.assign(document.createElement('b'),{textContent:'Nothing here yet'}),document.createTextNode('Lore adds memory as the chat talks.'))}else s.items.forEach(x=>{const row=document.createElement('article'),left=document.createElement('div'),text=document.createElement('div'),meta=document.createElement('div'),tag=document.createElement('span');row.className='item';text.className='item-title';text.textContent=x.text;meta.className='item-meta';meta.textContent=x.meta;tag.className='tag';tag.textContent=x.kind;left.append(text,meta);row.append(left,tag);items.append(row)});box.append(items);content.replaceChildren(box)}
  function render(d){model=normalize(d);$('chat-name').textContent=d.chat_guid||'Chat memory';$('fact-count').textContent=(d.facts||[]).length;$('people-count').textContent=Object.keys(d.people||{}).length;$('task-count').textContent=(d.open_tasks||[]).length;$('doc-count').textContent=(d.docs||[]).length;nav.replaceChildren();model.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.dataset.key=s.key;b.className=i?'':'active';b.textContent=s.label;b.onclick=()=>show(s.key);nav.append(b)});show('facts')}
  async function load(){auth.classList.add('hidden');app.classList.remove('hidden');content.innerHTML='<div class="loading"><div></div><div></div><div></div></div>';try{const r=await fetch(`${base}/api/v1/memory/${encodeURIComponent(guid)}`,{headers:{Accept:'application/json'}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'This memory link is not available.');render(d);localStorage.setItem('lore_memory_chat_guid',guid);const u=new URL(location.href);u.searchParams.set('chat',guid);history.replaceState(null,'',u)}catch(e){const box=document.createElement('div');box.className='error';box.textContent=e.message||'Could not load memory.';const b=document.createElement('button');b.className='retry';b.style.marginLeft='12px';b.textContent='Use another ID';b.onclick=()=>{app.classList.add('hidden');auth.classList.remove('hidden');guidInput.focus()};box.append(b);content.replaceChildren(box)}}
  form.onsubmit=e=>{e.preventDefault();guid=guidInput.value.trim();if(guid)load()};if(guid){guidInput.value=guid;load()}else guidInput.focus();
})();
